from __future__ import annotations

import os
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class EnvField:
    key: str
    default: str
    required: bool
    description: str


ENV_FIELDS: tuple[EnvField, ...] = (
    EnvField("DISCORD_TOKEN", "", True, "Discord user token"),
    EnvField("API_KEY", "", True, "AI API key"),
    EnvField("API_BASE_URL", "https://inference.do-ai.run/v1", False, "AI API base URL"),
    EnvField("MODEL_NAME", "openai-gpt-oss-120b", False, "AI model name"),
    EnvField("TRIGGER_PREFIX", "eva ", False, "Prefix used to trigger Eva"),
    EnvField(
        "RESPONSE_CONTEXT_MESSAGES",
        "40",
        False,
        "How many recent channel messages to include",
    ),
    EnvField("SERPER_API_KEY", "", False, "Serper API key (optional)"),
    EnvField("IMAGE_API_KEY", "", False, "Image API key (optional)"),
    EnvField("IMAGE_API_BASE_URL", "https://ai.6969.pro/v1", False, "Image API base URL"),
    EnvField("IMAGE_MODEL_NAME", "sonar", False, "Image model name"),
    EnvField("IMAGE_LANGUAGE", "en-US", False, "Image generation language"),
    EnvField("IMAGE_INCOGNITO", "true", False, "Image generation incognito mode"),
)


def is_linux_service_mode() -> bool:
    if not sys.platform.startswith("linux"):
        return False

    systemd_markers = (
        os.getenv("INVOCATION_ID"),
        os.getenv("JOURNAL_STREAM"),
        os.getenv("SYSTEMD_EXEC_PID"),
    )
    if any(marker for marker in systemd_markers):
        return True

    return not sys.stdin.isatty() and not sys.stdout.isatty()


def read_env_values(env_path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not env_path.exists():
        return values

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env_values(env_path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by Eva setup wizard",
        "# Edit values as needed",
        "",
    ]
    for field in ENV_FIELDS:
        lines.append(f"# {field.description}")
        lines.append(f"{field.key}={values.get(field.key, field.default)}")
        lines.append("")

    env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def run_env_setup_wizard(
    env_path: Path,
    *,
    input_fn: Callable[[str], str] = input,
    output_fn: Callable[[str], None] = print,
) -> None:
    existing = read_env_values(env_path)
    output_fn(f"Eva environment setup ({env_path})")
    output_fn("Press Enter to keep the current value shown in [brackets].")

    updated = dict(existing)
    for field in ENV_FIELDS:
        current = existing.get(field.key, field.default)
        prompt = f"{field.key} [{current}]: "
        response = input_fn(prompt).strip()
        value = response if response else current

        while field.required and not value:
            output_fn(f"{field.key} is required.")
            response = input_fn(prompt).strip()
            value = response if response else current

        updated[field.key] = value

    write_env_values(env_path, updated)
    output_fn(f"Saved environment file: {env_path}")


def tail_text_file(path: Path, *, lines: int) -> list[str]:
    if lines <= 0:
        return []
    if not path.exists():
        return []

    content = path.read_text(encoding="utf-8", errors="replace").splitlines()
    return content[-lines:]


def show_interaction_logs(
    log_path: Path,
    *,
    lines: int,
    output_fn: Callable[[str], None] = print,
) -> None:
    entries = tail_text_file(log_path, lines=lines)
    if not entries:
        output_fn(f"No interaction logs found at {log_path}")
        return

    output_fn(f"Showing last {len(entries)} interaction log lines from {log_path}")
    for entry in entries:
        output_fn(entry)
